# MONGO
MONGODB_DB = 'ims'
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017

#
# CELERY_RESULT_BACKEND = 'mongodb'
# CELERY_TASK_RESULT_EXPIRES = None
# CELERY_STORE_ERRORS_EVEN_IF_IGNORED = True
BROKER_URL = 'mongodb://localhost:27017/dqm'


